// Code generated by mockery v2.20.0. DO NOT EDIT.

package v1

import (
	userUsecase "backend/internal/domain/usecases/userUsecase"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserUsecase is an autogenerated mock type for the UserUsecase type
type MockUserUsecase struct {
	mock.Mock
}

type MockUserUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUsecase) EXPECT() *MockUserUsecase_Expecter {
	return &MockUserUsecase_Expecter{mock: &_m.Mock}
}

// DeleteById provides a mock function with given fields: ctx, dto
func (_m *MockUserUsecase) DeleteById(ctx context.Context, dto userUsecase.DeleteByIdRequest) error {
	ret := _m.Called(ctx, dto)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, userUsecase.DeleteByIdRequest) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserUsecase_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockUserUsecase_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - ctx context.Context
//   - dto userUsecase.DeleteByIdRequest
func (_e *MockUserUsecase_Expecter) DeleteById(ctx interface{}, dto interface{}) *MockUserUsecase_DeleteById_Call {
	return &MockUserUsecase_DeleteById_Call{Call: _e.mock.On("DeleteById", ctx, dto)}
}

func (_c *MockUserUsecase_DeleteById_Call) Run(run func(ctx context.Context, dto userUsecase.DeleteByIdRequest)) *MockUserUsecase_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(userUsecase.DeleteByIdRequest))
	})
	return _c
}

func (_c *MockUserUsecase_DeleteById_Call) Return(_a0 error) *MockUserUsecase_DeleteById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserUsecase_DeleteById_Call) RunAndReturn(run func(context.Context, userUsecase.DeleteByIdRequest) error) *MockUserUsecase_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// ReadById provides a mock function with given fields: ctx, dto
func (_m *MockUserUsecase) ReadById(ctx context.Context, dto userUsecase.ReadByIdRequest) (*userUsecase.ReadByIdResponse, error) {
	ret := _m.Called(ctx, dto)

	var r0 *userUsecase.ReadByIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, userUsecase.ReadByIdRequest) (*userUsecase.ReadByIdResponse, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, userUsecase.ReadByIdRequest) *userUsecase.ReadByIdResponse); ok {
		r0 = rf(ctx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userUsecase.ReadByIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, userUsecase.ReadByIdRequest) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUsecase_ReadById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadById'
type MockUserUsecase_ReadById_Call struct {
	*mock.Call
}

// ReadById is a helper method to define mock.On call
//   - ctx context.Context
//   - dto userUsecase.ReadByIdRequest
func (_e *MockUserUsecase_Expecter) ReadById(ctx interface{}, dto interface{}) *MockUserUsecase_ReadById_Call {
	return &MockUserUsecase_ReadById_Call{Call: _e.mock.On("ReadById", ctx, dto)}
}

func (_c *MockUserUsecase_ReadById_Call) Run(run func(ctx context.Context, dto userUsecase.ReadByIdRequest)) *MockUserUsecase_ReadById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(userUsecase.ReadByIdRequest))
	})
	return _c
}

func (_c *MockUserUsecase_ReadById_Call) Return(_a0 *userUsecase.ReadByIdResponse, _a1 error) *MockUserUsecase_ReadById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUsecase_ReadById_Call) RunAndReturn(run func(context.Context, userUsecase.ReadByIdRequest) (*userUsecase.ReadByIdResponse, error)) *MockUserUsecase_ReadById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateById provides a mock function with given fields: ctx, dto
func (_m *MockUserUsecase) UpdateById(ctx context.Context, dto userUsecase.UpdateByIdRequest) error {
	ret := _m.Called(ctx, dto)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, userUsecase.UpdateByIdRequest) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserUsecase_UpdateById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateById'
type MockUserUsecase_UpdateById_Call struct {
	*mock.Call
}

// UpdateById is a helper method to define mock.On call
//   - ctx context.Context
//   - dto userUsecase.UpdateByIdRequest
func (_e *MockUserUsecase_Expecter) UpdateById(ctx interface{}, dto interface{}) *MockUserUsecase_UpdateById_Call {
	return &MockUserUsecase_UpdateById_Call{Call: _e.mock.On("UpdateById", ctx, dto)}
}

func (_c *MockUserUsecase_UpdateById_Call) Run(run func(ctx context.Context, dto userUsecase.UpdateByIdRequest)) *MockUserUsecase_UpdateById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(userUsecase.UpdateByIdRequest))
	})
	return _c
}

func (_c *MockUserUsecase_UpdateById_Call) Return(_a0 error) *MockUserUsecase_UpdateById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserUsecase_UpdateById_Call) RunAndReturn(run func(context.Context, userUsecase.UpdateByIdRequest) error) *MockUserUsecase_UpdateById_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockUserUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUserUsecase creates a new instance of MockUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUserUsecase(t mockConstructorTestingTNewMockUserUsecase) *MockUserUsecase {
	mock := &MockUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
