// Code generated by mockery v2.20.0. DO NOT EDIT.

package v1

import (
	authUsecase "backend/internal/domain/usecases/authUsecase"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthUsecase is an autogenerated mock type for the AuthUsecase type
type MockAuthUsecase struct {
	mock.Mock
}

type MockAuthUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUsecase) EXPECT() *MockAuthUsecase_Expecter {
	return &MockAuthUsecase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, dto
func (_m *MockAuthUsecase) Login(ctx context.Context, dto authUsecase.LoginRequest) (authUsecase.LoginResponse, error) {
	ret := _m.Called(ctx, dto)

	var r0 authUsecase.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, authUsecase.LoginRequest) (authUsecase.LoginResponse, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, authUsecase.LoginRequest) authUsecase.LoginResponse); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(authUsecase.LoginResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, authUsecase.LoginRequest) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - dto authUsecase.LoginRequest
func (_e *MockAuthUsecase_Expecter) Login(ctx interface{}, dto interface{}) *MockAuthUsecase_Login_Call {
	return &MockAuthUsecase_Login_Call{Call: _e.mock.On("Login", ctx, dto)}
}

func (_c *MockAuthUsecase_Login_Call) Run(run func(ctx context.Context, dto authUsecase.LoginRequest)) *MockAuthUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(authUsecase.LoginRequest))
	})
	return _c
}

func (_c *MockAuthUsecase_Login_Call) Return(_a0 authUsecase.LoginResponse, _a1 error) *MockAuthUsecase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUsecase_Login_Call) RunAndReturn(run func(context.Context, authUsecase.LoginRequest) (authUsecase.LoginResponse, error)) *MockAuthUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, dto
func (_m *MockAuthUsecase) Register(ctx context.Context, dto authUsecase.RegisterRequest) error {
	ret := _m.Called(ctx, dto)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, authUsecase.RegisterRequest) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthUsecase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthUsecase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - dto authUsecase.RegisterRequest
func (_e *MockAuthUsecase_Expecter) Register(ctx interface{}, dto interface{}) *MockAuthUsecase_Register_Call {
	return &MockAuthUsecase_Register_Call{Call: _e.mock.On("Register", ctx, dto)}
}

func (_c *MockAuthUsecase_Register_Call) Run(run func(ctx context.Context, dto authUsecase.RegisterRequest)) *MockAuthUsecase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(authUsecase.RegisterRequest))
	})
	return _c
}

func (_c *MockAuthUsecase_Register_Call) Return(_a0 error) *MockAuthUsecase_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthUsecase_Register_Call) RunAndReturn(run func(context.Context, authUsecase.RegisterRequest) error) *MockAuthUsecase_Register_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockAuthUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockAuthUsecase creates a new instance of MockAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAuthUsecase(t mockConstructorTestingTNewMockAuthUsecase) *MockAuthUsecase {
	mock := &MockAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
