#!/bin/sh

if command -v golangci-lint >/dev/null 2>&1 ; then
    echo "golangci-lint found"
    echo "version: $(golangci-lint --version)\n"
else
    printf "golangci-lint not found. install...\n"
    curl -sSfL \
        https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |\ 
        sudo sh -s -- -b $(go env GOPATH)/bin latest;
fi



if command -v goose >/dev/null 2>&1 ; then
    echo "goose found"
    echo "version: $(goose --version)\n"
else
    printf "goose not found. install...\n"
    curl -fsSL \
        https://raw.githubusercontent.com/pressly/goose/master/install.sh |\
        sudo sh 
fi

