#!/bin/sh

if command -v goose >/dev/null 2>&1 ; then
    echo "goose found"
    echo "version: $(goose --version)"
else
    printf "goose not found. install..."
    curl -fsSL https://raw.githubusercontent.com/pressly/goose/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v3.5.0 
fi

if command -v golangci-lint >/dev/null 2>&1 ; then
    echo "golangci-lint found"
    echo "version: $(golangci-lint --version)"
else
    printf "golangci-lint not found. install..."
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3
fi
