// Code generated by mockery v2.20.0. DO NOT EDIT.

package authusecase

import (
	context "context"
	time "time"

	models "backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// MockConfirmEmailCodeService is an autogenerated mock type for the ConfirmEmailCodeService type
type MockConfirmEmailCodeService struct {
	mock.Mock
}

type MockConfirmEmailCodeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfirmEmailCodeService) EXPECT() *MockConfirmEmailCodeService_Expecter {
	return &MockConfirmEmailCodeService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockConfirmEmailCodeService) Get(ctx context.Context, key string) (*models.ConfirmEmailCode, error) {
	ret := _m.Called(ctx, key)

	var r0 *models.ConfirmEmailCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.ConfirmEmailCode, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.ConfirmEmailCode); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ConfirmEmailCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfirmEmailCodeService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConfirmEmailCodeService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockConfirmEmailCodeService_Expecter) Get(ctx interface{}, key interface{}) *MockConfirmEmailCodeService_Get_Call {
	return &MockConfirmEmailCodeService_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockConfirmEmailCodeService_Get_Call) Run(run func(ctx context.Context, key string)) *MockConfirmEmailCodeService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConfirmEmailCodeService_Get_Call) Return(_a0 *models.ConfirmEmailCode, _a1 error) *MockConfirmEmailCodeService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfirmEmailCodeService_Get_Call) RunAndReturn(run func(context.Context, string) (*models.ConfirmEmailCode, error)) *MockConfirmEmailCodeService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, data, ttl
func (_m *MockConfirmEmailCodeService) Set(ctx context.Context, data *models.ConfirmEmailCode, ttl time.Duration) error {
	ret := _m.Called(ctx, data, ttl)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ConfirmEmailCode, time.Duration) error); ok {
		r0 = rf(ctx, data, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfirmEmailCodeService_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockConfirmEmailCodeService_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - data *models.ConfirmEmailCode
//   - ttl time.Duration
func (_e *MockConfirmEmailCodeService_Expecter) Set(ctx interface{}, data interface{}, ttl interface{}) *MockConfirmEmailCodeService_Set_Call {
	return &MockConfirmEmailCodeService_Set_Call{Call: _e.mock.On("Set", ctx, data, ttl)}
}

func (_c *MockConfirmEmailCodeService_Set_Call) Run(run func(ctx context.Context, data *models.ConfirmEmailCode, ttl time.Duration)) *MockConfirmEmailCodeService_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.ConfirmEmailCode), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockConfirmEmailCodeService_Set_Call) Return(_a0 error) *MockConfirmEmailCodeService_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfirmEmailCodeService_Set_Call) RunAndReturn(run func(context.Context, *models.ConfirmEmailCode, time.Duration) error) *MockConfirmEmailCodeService_Set_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockConfirmEmailCodeService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockConfirmEmailCodeService creates a new instance of MockConfirmEmailCodeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockConfirmEmailCodeService(t mockConstructorTestingTNewMockConfirmEmailCodeService) *MockConfirmEmailCodeService {
	mock := &MockConfirmEmailCodeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
