apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  isDefault: true
  access: proxy
  editable: true
- name: Elasticsearch
  type: elasticsearch
  url: http://elasticsearch:9200
  access: proxy
  editable: true
  jsonData:
    index: 'fluentd-*'
    timeField: '@timestamp'