version: "3"


services:
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      # redis
      - "REDIS_URL=redis://admin:admin@redis:6379/0"
      # postgres
      - "POSTGRESQL_URL=postgresql://admin:admin@pgbouncer:6432/root"
      - "TRACE_GRPC_ADDR=otel_collector:4317"
      - "METRIC_GRPC_ADDR=otel_collector:12345"
    depends_on:
      - otel_collector
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - backend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "backend"
  fluentd:
    container_name: fluentd
    build:
      context: .
      dockerfile: fluentd.Dockerfile
    volumes:
      - ../configs/fluentd/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - backend
  otel_collector:
    container_name: otel_collector
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ../configs/otelcol/otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml
    command: --config /etc/otelcol/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "12345:12345" # otlp/spanmetrics grpc receiver
    depends_on:
      - jaeger
    networks:
      - backend



networks:
  backend:
