name: Backend
run-name: ${{ github.actor }} is build backend
on: [push]

jobs:
  Test-Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: make dependence
      - name: Generate code
        run: make generate
      - name: Test code
        run: make test
  Build-Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: make dependence
      - name: Generate code
        run: make generate
      - name: Build bin
        run: make build