name: Backend
run-name: ${{ github.actor }} is build backend
on: [push]

jobs:
  Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Audit code
        run: make audit