name: Frontend
run-name: ${{ github.actor }} is frontend
on: [push]

jobs:
  Frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        uses: |
          yarn
      - name: Start audit code
        run: make audit